accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout')
]

tasador_app/urls.py
from django.urls import path
from . import views

app_name = 'tasador_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('create_departamento/', views.crear_departamento, name='crear_depa'),
    path('create_casa/', views.crear_casa, name='crear_casa'),
    path('create_terreno/', views.crear_terreno, name='crear_terreno'),
    path('result_departamento/', views.tasador_result_departamento, name='result_depa'),
    path('result_casa/', views.tasador_result_casa, name='result_casa'),
    path('result_terreno/', views.tasador_result_terreno, name='result_terreno')
    ]

tasador_final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('', include('tasador_app.urls')),
    #path('tasador/',include('tasador_app.urls'))
]

tasador_app/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.auth.models import User

DISTRICT_CHOICES_DEPARTAMENTOS = (
    ('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Bellavista', 'Bellavista'), ('Breña', 'Breña'),
    ('Callao', 'Callao'), ('Carabayllo', 'Carabayllo'), ('Cercado de Lima', 'Cercado de Lima'),
    ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Comas', 'Comas'),
    ('El Agustino', 'El Agustino'), ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Perla', 'La Perla'),
    ('La Punta', 'La Punta'), ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'),
    ('Lurin', 'Lurin'), ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'),
    ('Pachacamac', 'Pachacamac'), ('Pueblo Libre', 'Pueblo Libre'), ('Puente Piedra', 'Puente Piedra'),
    ('Punta Hermosa', 'Punta Hermosa'), ('Rimac', 'Rimac'), ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'),
    ('San Isidro', 'San Isidro'), ('San Juan de Lurigancho', 'San Juan de Lurigancho'),
    ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'),
    ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Anita', 'Santa Anita'),
    ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santa Rosa', 'Santa Rosa'),
    ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo'), ('Ventanilla', 'Ventanilla'),
    ('Villa El Salvador', 'Villa El Salvador')
)

class Departamento(models.Model):
    distrito = models.CharField(max_length=100, choices=DISTRICT_CHOICES_DEPARTAMENTOS, default='Escoge distrito')
    area = models.FloatField()
    dormitorios = models.IntegerField()
    baños = models.IntegerField()
    ubicacion = models.PointField(default=Point( -77.0282, -12.0432, srid=4326))
    empresario = models.ForeignKey(User, default=None, on_delete='CASCADE')

DISTRICT_CHOICES_CASAS = (
    ('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Bellavista', 'Bellavista'), ('Breña', 'Breña'),
    ('Callao', 'Callao'), ('Carabayllo', 'Carabayllo'), ('Cercado de Lima', 'Cercado de Lima'),
    ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Cieneguilla', 'Cieneguilla'),
    ('Comas', 'Comas'), ('El Agustino', 'El Agustino'), ('Independencia', 'Independencia'),
    ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Perla', 'La Perla'), ('La Punta', 'La Punta'),
    ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'), ('Lurin', 'Lurin'),
    ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'), ('Pachacamac', 'Pachacamac'), ('Pucusana', 'Pucusana'),
    ('Pueblo Libre', 'Pueblo Libre'), ('Puente Piedra', 'Puente Piedra'), ('Punta Hermosa', 'Punta Hermosa'),
    ('Punta Negra', 'Punta Negra'), ('Rimac', 'Rimac'),  ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'),
    ('San Isidro', 'San Isidro'),  ('San Juan de Lurigancho', 'San Juan de Lurigancho'),
    ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'),
    ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Anita', 'Santa Anita'),
    ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santa Rosa', 'Santa Rosa'),
    ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo'), ('Ventanilla', 'Ventanilla'),
    ('Villa El Salvador', 'Villa El Salvador'), ('Villa Maria del Triunfo', 'Villa Maria del Triunfo')
)

class Casa(models.Model):
    distrito = models.CharField(max_length=100, choices=DISTRICT_CHOICES_CASAS, default='Escoge distrito')
    area = models.FloatField()
    dormitorios = models.IntegerField()
    baños = models.IntegerField()
    ubicacion = models.PointField(default=Point( -77.0282, -12.0432, srid=4326))
    empresario = models.ForeignKey(User, default=None, on_delete='CASCADE')

DISTRICT_CHOICES_TERRENOS = (
    ('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Bellavista', 'Bellavista'), ('Breña', 'Breña'),
    ('Callao', 'Callao'), ('Carabayllo', 'Carabayllo'), ('Carmen De La Legua Reynoso', 'Carmen De La Legua Reynoso'),
    ('Cercado de Lima', 'Cercado de Lima'),
    ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Cieneguilla', 'Cieneguilla'),
    ('Comas', 'Comas'), ('El Agustino', 'El Agustino'), ('Independencia', 'Independencia'),
    ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Perla', 'La Perla'),
    ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'), ('Lurin', 'Lurin'),
    ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'), ('Pachacamac', 'Pachacamac'), ('Pucusana', 'Pucusana'),
    ('Pueblo Libre', 'Pueblo Libre'), ('Puente Piedra', 'Puente Piedra'), ('Punta Hermosa', 'Punta Hermosa'),
    ('Punta Negra', 'Punta Negra'), ('Rimac', 'Rimac'),  ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'),
    ('San Isidro', 'San Isidro'),  ('San Juan de Lurigancho', 'San Juan de Lurigancho'),
    ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'),
    ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Anita', 'Santa Anita'),
    ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santa Rosa', 'Santa Rosa'),
    ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo'), ('Ventanilla', 'Ventanilla'),
    ('Villa El Salvador', 'Villa El Salvador'), ('Villa Maria del Triunfo', 'Villa Maria del Triunfo')
)

class Terreno(models.Model):
    distrito = models.CharField(max_length=100, choices=DISTRICT_CHOICES_TERRENOS, default='Escoge distrito')
    area = models.FloatField()
    ubicacion = models.PointField(default=Point(-77.0282, -12.0432, srid=4326))
    empresario = models.ForeignKey(User, default=None, on_delete='CASCADE')

tasador_app/forms.py
from django import forms
from . import models
from mapwidgets.widgets import GooglePointFieldWidget


class createDepartamento(forms.ModelForm):
    class Meta:
        model = models.Departamento
        fields = ["distrito", "area", "dormitorios", "baños", "ubicacion"]

        widgets = {
            'ubicacion': GooglePointFieldWidget,
        }

class createCasa(forms.ModelForm):
    class Meta:
        model = models.Casa
        fields = ["distrito", "area", "dormitorios", "baños", "ubicacion"]

        widgets = {
            'ubicacion': GooglePointFieldWidget,
        }


class createTerreno(forms.ModelForm):
    class Meta:
        model = models.Terreno
        fields = ["distrito", "area", "ubicacion"]

        widgets = {
            'ubicacion': GooglePointFieldWidget,
        }

tasador_app/views.py
import time
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from tasador_app.scripts.regression import make_regression, make_regression2
from . import forms
from .models import Departamento, Casa, Terreno

def home(request):
    return render(request, 'tasador_app/home.html')

#def tasador_list(request):
#    lista_inmuebles = Departamento.objects.all().order_by('area')
#    return render(request, 'tasador_app/tasador_list.html', {'lista_inmuebles': lista_inmuebles})

def tasador_result_departamento(request):
    dict_distritos = {'Ancon':0, 'Ate':0, 'Barranco':0, 'Bellavista':0,'Breña':0, 'Callao':0, 'Carabayllo':0,
                      'Cercado de Lima':0, 'Chaclacayo':0, 'Chorrillos':0, 'Chosica':0, 'Comas':0, 'El Agustino':0,
                      'Jesus Maria':0, 'La Molina':0, 'La Perla':0, 'La Punta':0, 'La Victoria':0, 'Lince':0,
                      'Los Olivos':0, 'Lurin':0, 'Magdalena del Mar':0, 'Miraflores':0, 'Pachacamac': 0, 'Pueblo Libre':0,
                      'Puente Piedra':0, 'Punta Hermosa':0, 'Rimac':0, 'San Bartolo':0, 'San Borja':0, 'San Isidro':0,
                      'San Juan de Lurigancho':0, 'San Juan de Miraflores':0, 'San Luis':0, 'San Martin de Porres':0,
                      'San Miguel':0, 'Santa Anita':0, 'Santa Maria del Mar':0, 'Santa Rosa':0,'Santiago de Surco':0,
                      'Surquillo':0, 'Ventanilla':0, 'Villa El Salvador':0}

    #print(dict_distritos)
    inmueble = Departamento.objects.last()

    dict_distritos[inmueble.distrito] = 1
    valores_distritos = list(dict_distritos.values())

    lat, long = inmueble.ubicacion.y, inmueble.ubicacion.x

    inicio = time.time()
    precio_reg = make_regression('departamentos',inmueble.area, inmueble.dormitorios, inmueble.baños, valores_distritos, lat, long)
    print(inicio-time.time())

    precio_reg_soles = round(precio_reg * 3.46,2)
    return render(request, 'tasador_app/tasador_result_depa.html', {'inmueble': inmueble, 'precio_reg': precio_reg,
                                                               'precio_reg_soles':precio_reg_soles})

def tasador_result_casa(request):
    dict_distritos = {'Ancon':0, 'Ate':0, 'Barranco':0, 'Bellavista':0,'Breña':0, 'Callao':0, 'Carabayllo':0,
                      'Cercado de Lima':0, 'Chaclacayo':0, 'Chorrillos':0, 'Chosica':0, 'Cieneguilla':0,'Comas':0,
                      'El Agustino':0, 'Independencia':0, 'Jesus Maria':0, 'La Molina':0, 'La Perla':0, 'La Punta':0,
                      'La Victoria':0, 'Lince':0, 'Los Olivos':0, 'Lurin':0, 'Magdalena del Mar':0, 'Miraflores':0,
                      'Pachacamac': 0, 'Pucusana':0, 'Pueblo Libre':0, 'Puente Piedra':0, 'Punta Hermosa':0, 'Punta Negra':0,'Rimac':0,
                      'San Bartolo':0, 'San Borja':0, 'San Isidro':0, 'San Juan de Lurigancho':0,
                      'San Juan de Miraflores':0, 'San Luis':0, 'San Martin de Porres':0, 'San Miguel':0,
                      'Santa Anita':0, 'Santa Maria del Mar':0, 'Santa Rosa':0,'Santiago de Surco':0, 'Surquillo':0,
                      'Ventanilla':0, 'Villa El Salvador':0, 'Villa Maria del Triunfo':0}

    inmueble = Casa.objects.last()

    dict_distritos[inmueble.distrito] = 1
    valores_distritos = list(dict_distritos.values())

    lat, long = inmueble.ubicacion.y, inmueble.ubicacion.x

    inicio = time.time()
    precio_reg = make_regression('casas', inmueble.area, inmueble.dormitorios, inmueble.baños, valores_distritos, lat, long)
    print(inicio-time.time())

    precio_reg_soles = round(precio_reg * 3.46,2)
    return render(request, 'tasador_app/tasador_result_casa.html', {'inmueble': inmueble, 'precio_reg': precio_reg,
                                                               'precio_reg_soles':precio_reg_soles})


def tasador_result_terreno(request):
    dict_distritos = {'Ancon': 0, 'Ate': 0, 'Barranco': 0, 'Bellavista': 0, 'Breña': 0, 'Callao': 0, 'Carabayllo': 0,
                      'Carmen De La Legua Reynoso': 0,
                      'Cercado de Lima': 0, 'Chaclacayo': 0, 'Chorrillos': 0, 'Chosica': 0, 'Cieneguilla': 0,
                      'Comas': 0,
                      'El Agustino': 0, 'Independencia': 0, 'Jesus Maria': 0, 'La Molina': 0, 'La Perla': 0,
                      'La Victoria': 0, 'Lince': 0, 'Los Olivos': 0, 'Lurin': 0, 'Magdalena del Mar': 0,
                      'Miraflores': 0,
                      'Pachacamac': 0, 'Pucusana': 0, 'Pueblo Libre': 0, 'Puente Piedra': 0, 'Punta Hermosa': 0,
                      'Punta Negra': 0, 'Rimac': 0,
                      'San Bartolo': 0, 'San Borja': 0, 'San Isidro': 0, 'San Juan de Lurigancho': 0,
                      'San Juan de Miraflores': 0, 'San Luis': 0, 'San Martin de Porres': 0, 'San Miguel': 0,
                      'Santa Anita': 0, 'Santa Maria del Mar': 0, 'Santa Rosa': 0, 'Santiago de Surco': 0,
                      'Surquillo': 0,
                      'Ventanilla': 0, 'Villa El Salvador': 0, 'Villa Maria del Triunfo': 0}

    inmueble = Terreno.objects.last()

    dict_distritos[inmueble.distrito] = 1
    valores_distritos = list(dict_distritos.values())

    lat, long = inmueble.ubicacion.y, inmueble.ubicacion.x

    precio_reg = make_regression2('terrenos', inmueble.area, valores_distritos, lat, long)
    precio_reg_soles = round(precio_reg * 3.46,2)
    return render(request, 'tasador_app/tasador_result_terreno.html', {'inmueble': inmueble, 'precio_reg': precio_reg,
                                                                       'precio_reg_soles': precio_reg_soles})

@login_required(login_url="/accounts/login/")
def crear_departamento(request):
    if request.method == 'POST':
        form = forms.createDepartamento(request.POST)
        if form.is_valid():
            instace = form.save(commit=False)
            instace.empresario = request.user
            instace.save()
            return redirect('tasador_app:result_depa')
    else:
        form = forms.createDepartamento()
    return render(request, 'tasador_app/build_create_departamento.html', {'form':form})

@login_required(login_url="/accounts/login/")
def crear_casa(request):
    if request.method == 'POST':
        form = forms.createCasa(request.POST)
        if form.is_valid():
            instace = form.save(commit=False)
            instace.empresario = request.user
            instace.save()
            return redirect('tasador_app:result_casa')
    else:
        form = forms.createCasa()
    return render(request, 'tasador_app/build_create_casa.html', {'form':form})

@login_required(login_url="/accounts/login/")
def crear_terreno(request):
    if request.method == 'POST':
        form = forms.createTerreno(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.empresario = request.user
            instance.save()
            return redirect('tasador_app:result_terreno')
    else:
        form = forms.createTerreno()
    return render(request, 'tasador_app/build_create_terreno.html', {'form':form})

tasador_app/templates/tasador_app/build_create_casa.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">

    <title>Crear Casa</title>
</head>
<body>
    {% block title %}
    <h2>Coloque los datos de su casa</h2>
    {% endblock %}

    {% block content %}
    <div class="insert-build">

        <form class="site-form" action="{% url 'tasador_app:crear_casa' %}" method="post">
            {% csrf_token %}
            <h3> Usando el mapa, señale la ubicación de su inmueble con el marcador</h3>
            {{form.media}}
            {{form.as_ul}}

            <script type="text/javascript">

            </script>

            {% buttons %}
            <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "home" %} Tasar
            </button>
            {% endbuttons %}
        </form>
    </div>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/build_create_departamento.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">

    <title>Crear Departamento</title>
</head>
<body>
    {% block title %}
    <h2>Coloque los datos de su departamento</h2>
    {% endblock %}

    {% block content %}
    <div class="insert-build">

        <form class="site-form" action="{% url 'tasador_app:crear_depa' %}" method="post">
            {% csrf_token %}
            <h3> Usando el mapa, señale la ubicación de su inmueble con el marcador</h3>
            {{form.media}}
            {{form.as_ul}}

            <script type="text/javascript">

            </script>

            {% buttons %}
            <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "home" %} Tasar
            </button>
            {% endbuttons %}
        </form>
    </div>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/build_create_terreno.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">

    <title>Crear Terreno</title>
</head>
<body>
    {% block title %}
    <h2>Coloque los datos de su terreno</h2>
    {% endblock %}

    {% block content %}
    <div class="insert-build">

        <form class="site-form" action="{% url 'tasador_app:crear_terreno' %}" method="post">
            {% csrf_token %}
            <h3> Usando el mapa, señale la ubicación de su inmueble con el marcador</h3>
            {{form.media}}
            {{form.as_ul}}

            <script type="text/javascript">

            </script>

            {% buttons %}
            <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "home" %} Tasar
            </button>
            {% endbuttons %}
        </form>
    </div>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasador</title>
</head>
<body>
    {% block title %}
    <h1>Bienvenido al Tasador de Prestamype</h1>

    {% endblock %}

    {% block content %}
    <ul>
        <li><a href="{% url 'tasador_app:crear_depa' %}">Tasar Departamento</a></li>
        <li><a href="{% url 'tasador_app:crear_casa' %}">Tasar Casa</a></li>
        <li><a href="{% url 'tasador_app:crear_terreno' %}">Tasar Terreno</a></li>
    </ul>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/tasador_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasador</title>
</head>
<body>
    {% block title %}
    <h1>Inmueble</h1>
    {% endblock %}

    {% block content %}
    <div class="lista_inmuebles">
        {% for inmueble in lista_inmuebles %}
            <div class="inmueble">
                <h3><a>Area: {{inmueble.area}}</a></h3>
                <h3>Nº cuartos: {{inmueble.cuartos}}</h3>
                <h3>Nº baños: {{inmueble.aseos}}</h3>
            </div>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/tasador_result_casa.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultado Tasacion</title>
</head>
<body>
    {% block title %}
    <h1>Resultado Tasacion</h1>
    {% endblock %}

    {% block content %}
    <div class="inmueble">
        <h3>Usuario: {{inmueble.empresario}}</h3>
        <h3>Distrito: {{inmueble.distrito}}</h3>
        <h3>Area: {{inmueble.area}}</h3>
        <h3>Nº de dormitorios: {{inmueble.dormitorios}}</h3>
        <h3>Nº de baños: {{inmueble.baños}}</h3>
        <h3>Latitud: {{inmueble.ubicacion.y}}</h3>
        <h3>Longitud: {{inmueble.ubicacion.x}}</h3>
    </div>
    <h1> La casa está tasada en $ {{precio_reg}} o S/. {{precio_reg_soles}}</h1>
    <a href="{% url 'tasador_app:crear_casa' %}">Atrás</a>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/tasador_result_depa.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultado Tasacion</title>
</head>
<body>
    {% block title %}
    <h1>Resultado Tasacion</h1>
    {% endblock %}

    {% block content %}
    <div class="inmueble">
        <h3>Usuario: {{inmueble.empresario}}</h3>
        <h3>Distrito: {{inmueble.distrito}}</h3>
        <h3>Area: {{inmueble.area}}</h3>
        <h3>Nº de dormitorios: {{inmueble.dormitorios}}</h3>
        <h3>Nº de baños: {{inmueble.baños}}</h3>
        <h3>Latitud: {{inmueble.ubicacion.y}}</h3>
        <h3>Longitud: {{inmueble.ubicacion.x}}</h3>
    </div>
    <h1> El departamento está tasado en $ {{precio_reg}} o S/. {{precio_reg_soles}}</h1>
    <a href="{% url 'tasador_app:crear_depa' %}">Atrás</a>
    {% endblock %}
</body>
</html>

tasador_app/templates/tasador_app/tasador_result_terreno.html
{% extends 'base.html' %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultado Tasacion</title>
</head>
<body>
    {% block title %}
    <h1>Resultado Tasacion</h1>
    {% endblock %}

    {% block content %}
    <div class="inmueble">
        <h3>Usuario: {{inmueble.empresario}}</h3>
        <h3>Distrito: {{inmueble.distrito}}</h3>
        <h3>Area: {{inmueble.area}}</h3>
        <h3>Latitud: {{inmueble.ubicacion.y}}</h3>
        <h3>Longitud: {{inmueble.ubicacion.x}}</h3>
    </div>
    <h1> El terreno está tasado en $ {{precio_reg}} o S/. {{precio_reg_soles}}</h1>
    <a href="{% url 'tasador_app:crear_terreno' %}">Atrás</a>
    {% endblock %}
</body>
</html>