accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout')
]

tasador_app/urls.py
from django.urls import path
from . import views

app_name = 'tasador_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('create_departamento/', views.crear_departamento, name='crear_depa'),
    path('create_casa/', views.crear_casa, name='crear_casa'),
    path('create_terreno/', views.crear_terreno, name='crear_terreno'),
    path('result_departamento/', views.tasador_result_departamento, name='result_depa'),
    path('result_casa/', views.tasador_result_casa, name='result_casa'),
    path('result_terreno/', views.tasador_result_terreno, name='result_terreno')
    ]

tasador_final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('', include('tasador_app.urls')),
    #path('tasador/',include('tasador_app.urls'))
]

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'tasador_app:home' %}">Prestamype</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'tasador_app:home' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                 <li><a>Hola {{user.username}}</a></li>
                 <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}

            </ul>
        </div>
    </nav>

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Bienvenidos al tasador</h1>
</body>
</html>